#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
#
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := library_code/hx711.cpp

# header files in this project
HEADERS := library_code/hx711.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory
# and defer to the appropriate Makefile.* there
RELATIVE := $(RELATIVE)../..
include $(RELATIVE)/Makefile.due
